insert into Players values(401,'Virgil van Dijk','Center Back',19,'https://www.fifaratings.com/wp-content/uploads/22_180-15.png')
insert into Players values(402,'Frenkie de Jong',' Center Midfielder',19,'https://www.fifaratings.com/wp-content/uploads/22_180-34.png')
insert into Players values(403,'Matthijs de Ligt','Center Back',19,'https://www.fifaratings.com/wp-content/uploads/22_180-94.png')
insert into Players values(404,'Memphis Depay','Center Forward',19,'https://www.fifaratings.com/wp-content/uploads/22_180-82.png')
insert into Players values(405,'Stefan de Vrij','Center Back',19,'https://www.fifaratings.com/wp-content/uploads/22_180-83.png')
insert into Players values(406,'Georginio Wijnaldum','Center Midfielder',19,'https://www.fifaratings.com/wp-content/uploads/22_180-122.png')
insert into Players values(407,'Wout Weghorst','Striker',19,'https://www.fifaratings.com/wp-content/uploads/22_180-179.png')
insert into Players values(408,'Denzel Dumfries','Right Back',19,'https://www.fifaratings.com/wp-content/uploads/22_180-203.png')
insert into Players values(409,'Marten de Roon','Center Defensive Midfielder',19,'https://www.fifaratings.com/wp-content/uploads/22_180-253.png')
insert into Players values(410,'Daley Blind','Center Back',19,'https://www.fifaratings.com/wp-content/uploads/22_180-270.png')
 
insert into Players values(80,'Ronaldo Jailson Cabrais Petri','Right Midfielder',20,'https://www.fifaratings.com/wp-content/uploads/22_180-173.png')
insert into Players values(81,'Josué Durval Chiamulera Vaz','Center Back',20,'https://www.fifaratings.com/wp-content/uploads/22_180-229.png')
insert into Players values(82,'Raphael William Anjos Rochedo','GoalKeeper',20,'https://www.fifaratings.com/wp-content/uploads/22_180-230.png')
insert into Players values(83,'Adryan Juliano Zonta Torres','Left Wing Back',20,'https://www.fifaratings.com/wp-content/uploads/22_180-382.png')
insert into Players values(84,'Welington Kauê Dano Nascimento','Left Back',20,'https://www.fifaratings.com/wp-content/uploads/22_180-295.png')
insert into Players values(85,'Rosberto J. Dourado Santos','Center Defensive Midfielder',20,'https://www.fifaratings.com/wp-content/uploads/22_180-370.png')
insert into Players values(86,'Juan Everton Mestres de Mesquita','Center Back',20,'https://www.fifaratings.com/wp-content/uploads/22_180-383.png')
insert into Players values(87,'Lourival Adnan Beretta Barbosa','Striker',20,'https://www.fifaratings.com/wp-content/uploads/22_180-302.png')
insert into Players values(88,'Marvin Oswaldo Rangel Azevedo','Striker',20,'https://www.fifaratings.com/wp-content/uploads/22_180-296.png')
insert into Players values(89,'Maikel Renan Catarino Fagundes','Right Back',20,'https://www.fifaratings.com/wp-content/uploads/22_180-488.png')

insert into Players values(110,'Kasper Schmeichel','GoalKeeper',21,'https://www.fifaratings.com/wp-content/uploads/22_180-80.png')
insert into Players values(111,'Pierre-Emile Højbjerg','Center Defensive Midfielder',21,'https://www.fifaratings.com/wp-content/uploads/22_180-143.png')
insert into Players values(112,'Simon Kjær','Center Back',21,'https://www.fifaratings.com/wp-content/uploads/22_180-185.png')
insert into Players values(113,'Christian Eriksen','Center Midfielder',21,'https://www.fifaratings.com/wp-content/uploads/22_180-283.png')
insert into Players values(114,'Thomas Delaney','Center Back',21,'https://www.fifaratings.com/wp-content/uploads/22_180-334.png')
insert into Players values(115,'Andreas Christensen','Center Back',21,'https://www.fifaratings.com/wp-content/uploads/22_180-444.png')
insert into Players values(116,'Daniel Wass','Right Back',21,'https://www.fifaratings.com/wp-content/uploads/22_180-415.png')
insert into Players values(117,'Kasper Dolberg','Striker',21,'https://www.fifaratings.com/wp-content/uploads/22_180-554.png')
insert into Players values(118,'Jannik Vestergaard','Center Back',21,'https://www.fifaratings.com/wp-content/uploads/22_180-711.png')
insert into Players values(119,'Mikkel Damsgaard','Center Attacking Midfielder',21,'https://www.fifaratings.com/wp-content/uploads/22_180-1086.png')

insert into Players values(90,'Raúl Jiménez','Striker',22,'https://www.fifaratings.com/wp-content/uploads/22_180-150.png')
insert into Players values(91,'Jesús Corona','Right Midfielder',22,'https://www.fifaratings.com/wp-content/uploads/22_180-265.png')
insert into Players values(92,'Hirving Lozano','Right Wing',22,'https://www.fifaratings.com/wp-content/uploads/22_180-358.png')
insert into Players values(93,'Héctor Herrera','Center Midfielder',22,'https://www.fifaratings.com/wp-content/uploads/22_180-323.png')
insert into Players values(94,'Guillermo Ochoa','GoalKeeper',22,'https://www.fifaratings.com/wp-content/uploads/22_180-409.png')
insert into Players values(95,'Andrés Guardado','Center Defensive Midfielder',22,'https://www.fifaratings.com/wp-content/uploads/22_180-813.png')
insert into Players values(96,'Edson Álvarez','Center Back',22,'https://www.fifaratings.com/wp-content/uploads/22_180-1022.png')
insert into Players values(97,'Luis Romo','Center Back',22,'https://www.fifaratings.com/wp-content/uploads/22_180-1015.png')
insert into Players values(98,'Orbelín Pineda','Right Midfielder',22,'https://www.fifaratings.com/wp-content/uploads/22_180-971.png')
insert into Players values(99,'Rogelio Funes Mori','Striker',22,'https://www.fifaratings.com/wp-content/uploads/22_180-891.png')

insert into Players values(00,'Robert Lewandowski','Striker',23,'https://www.fifaratings.com/wp-content/uploads/22_180-1.png')
insert into Players values(01,'Wojciech Szczęsny','GoalKeeper',23,'https://www.fifaratings.com/wp-content/uploads/22_180-38.png')
insert into Players values(02,'Piotr Zieliński','Center Attacking Midfielder',23,'https://www.fifaratings.com/wp-content/uploads/22_180-380.png')
insert into Players values(03,'Bartłomiej Drągowski','GoalKeeper',23,'https://www.fifaratings.com/wp-content/uploads/22_180-873.png')
insert into Players values(04,'Grzegorz Krychowiak','Center Defensive Midfielder',23,'https://www.fifaratings.com/wp-content/uploads/22_180-406.png')
insert into Players values(05,'Jan Bednarek','Center Back',23,'https://www.fifaratings.com/wp-content/uploads/22_180-1203.png')
insert into Players values(06,'Krzysztof Piątek','Striker',23,'https://www.fifaratings.com/wp-content/uploads/22_180-1175.png')
insert into Players values(07,'Tomasz Kędziora','Right Back',23,'https://www.fifaratings.com/wp-content/uploads/22_180-1807.png')
insert into Players values(08,'Łukasz Skorupski','GoalKeeper',23,'https://www.fifaratings.com/wp-content/uploads/22_180-1809.png')
insert into Players values(09,'Maciej Rybus','LeftBack',23,'https://www.fifaratings.com/wp-content/uploads/22_180-1632.png')

insert into Players values(20,'Marcel Sabitzer','Center Midfielder',24,'https://www.fifaratings.com/wp-content/uploads/22_180-120.png')
insert into Players values(21,'David Alaba','Center Back',24,'https://www.fifaratings.com/wp-content/uploads/22_180-129.png')
insert into Players values(22,'Konrad Laimer','Right Wing Back',24,'https://www.fifaratings.com/wp-content/uploads/22_180-349.png')
insert into Players values(23,'Marko Arnautović','Striker',24,'https://www.fifaratings.com/wp-content/uploads/22_180-330.png')
insert into Players values(24,'Xaver Schlager','Center Defensive Midfielder',24,'https://www.fifaratings.com/wp-content/uploads/22_180-388.png')
insert into Players values(25,'Martin Hinteregger','Center Back',24,'https://www.fifaratings.com/wp-content/uploads/22_180-505.png')
insert into Players values(26,'Christoph Baumgartner','Center Attacker Midfielder',24,'https://www.fifaratings.com/wp-content/uploads/22_180-849.png')
insert into Players values(27,'Florian Grillitsch','Center Midfielder',24,'https://www.fifaratings.com/wp-content/uploads/22_180-719.png')
insert into Players values(28,'Christopher Trimmel','Right Wing Back',24,'https://www.fifaratings.com/wp-content/uploads/22_180-1110.png')
insert into Players values(29,'Philipp Lienhart','Center Back',24,'https://www.fifaratings.com/wp-content/uploads/22_180-1417.png')

insert into Players values(30,'Zlatan Ibrahimović','Striker',25,'https://www.fifaratings.com/wp-content/uploads/22_180-126.png')
insert into Players values(31,'Alexander Isak','Striker',25,'https://www.fifaratings.com/wp-content/uploads/22_180-201.png')
insert into Players values(32,'Dejan Kulusevski','Left Midfielder',25,'https://www.fifaratings.com/wp-content/uploads/22_180-299.png')
insert into Players values(33,'Emil Forsberg','Center Attacking Midfielder',25,'https://www.fifaratings.com/wp-content/uploads/360-51-300x300.png')
insert into Players values(34,'Victor Lindelöf','Center Defensive Midfielder',25,'https://www.fifaratings.com/wp-content/uploads/22_180-472.png')
insert into Players values(35,'Jordan Larsson','Center Attacking Midfielder',25,'https://www.fifaratings.com/wp-content/uploads/22_180-969.png')
insert into Players values(36,'Ludwig Augustinsson','Left Back',25,'https://www.fifaratings.com/wp-content/uploads/22_180-1151.png')
insert into Players values(37,'Viktor Claesson','Center Attacking Midfielder',25,'https://www.fifaratings.com/wp-content/uploads/22_180-1223.png')
insert into Players values(38,'Albin Ekdal','Center Midfielder',25,'https://www.fifaratings.com/wp-content/uploads/22_180-1432.png')
insert into Players values(39,'Robin Olsen','GoalKeeper',25,'https://www.fifaratings.com/wp-content/uploads/22_180-1224.png')